name: Build Flutter AAB

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'

      - name: Install dependencies
        run: flutter pub get

      - name: Set version dynamically
        run: |
          VERSION_NAME="1.0.0"
          VERSION_CODE=${{ github.run_number }}
          sed -i "s/^version:.*/version: $VERSION_NAME+$VERSION_CODE/" pubspec.yaml

      - name: Build AAB
        run: flutter build appbundle --release

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release.aab
          path: build/app/outputs/bundle/release/app-release.aab

